#!/bin/sh
# Copyright (C) 2012 Havlena Petr <havlenapetr@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
cat << EOF
Usage:
$0 -i <input> -t <tool> [-f <format>] ...
    -i <input>     Input pk4 base folder
    -t <tool>      Binary used for texture compression
    -f <format>    Compression format [PVRTC4, PVRTC2, ETC]

EOF
}

get_file_ext()
{
    format=$(echo $1 | awk '{print toupper($0)}')
    case "$format" in
        "PVRTC4")
            echo "pvr"
            ;;
        "PVRTC2")
            echo "pvr"
            ;;
        "ETC")
            echo "pkm"
            ;;
    esac
    echo ""
}

#
# $1    Directory where we should find textures
# $2    Binary for texture compressing
# $3    Compression format
#
compress_textures()
{
    find $1 -name \*.tga |
    while read texture
    do
        ext=$(get_file_ext $3)
        outfile=$1"/"$ext""${texture#$1}
        mkdir -p $outfile
        $2 -i$texture -f$3 -o$outfile
        rmdir $outfile
    done
}

#
# $1    Directory which contains .pk4 files
# $2    Binary for texture compressing
#
do_compression()
{
    echo "****************************************************"
    for pk_file in $1"/"*.pk4
    do
        echo "Processing pak file: "$pk_file
        pk_dir="${pk_file%*.pk4}"
        rm -rf $pk_dir
        unzip -d $pk_dir $pk_file > /dev/null
        compress_textures $pk_dir $2 $3
        cd $pk_dir
        zip -r -g $pk_file * > /dev/null
        cd ..
        rm -rf $pk_dir
        echo "****************************************************"
    done
}

input_dir=
pvrtc_bin=
pvrtc_fmt="PVRTC2"

while [ $# -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in
        "-i")
            input_dir="$1"
            shift
            ;;
        "-t")
            pvrtc_bin="$1"
            shift
            ;;
        "-f")
            pvrtc_fmt="$1"
            shift
            ;;
        "-h")
            usage
            exit 0
            ;;
    esac
done

if [ -d "${input_dir}" ]; then
    if [ ! -z "$(get_file_ext $pvrtc_fmt)" ]; then
        if [ -f "${pvrtc_bin}" ]; then
            do_compression $input_dir $pvrtc_bin $pvrtc_fmt
        else
            printf "ERROR: PVRTC binary not specified\n" >&2
            usage >&2
            exit 0
        fi
    else
        printf "ERROR: Bad compression format\n" >&2
        usage >&2
        exit 0
    fi
else
    printf "ERROR: Input dir not specified\n" >&2
    usage >&2
    exit 0
fi
